name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run ESLint
        run: yarn eslint . --max-warnings=0

      - name: Type check
        run: yarn tsc --noEmit
